interface Project {
  title: string
  description: string
  href?: string
  liveSrc?: string
  imgSrc?: string
}

const projectsData: Project[] = [
  {
    title: 'this site!',
    description: `No fluff, just the good stuff!`,
    imgSrc: '/static/images/emangini-hero.png',
    href: 'https://github.com/edtbl76/emangini-tailwind-nextjs-contentlayer',
  },
  {
    title: 'STUD.io ControlRoom',
    description: `ControlRoom is a private studio asset management application for cataloging and organizing recording studio gear,
  plugins, and sample libraries. The frontend is built on Next.js (App Router) with TypeScript, TanStack Query for
  server-state management, TanStack Table for virtualized data grids, Tailwind CSS and shadcn/ui for styling,
  and Playwright for end-to-end testing. The backend is FastAPI with asyncpg for async PostgreSQL access, Pydantic for schema validation,
  python-jose for JWT auth, and OpenPyxl for xlsx import/export with dropdown validation. PostgreSQL handles full-text search
  via tsvector/websearch_to_tsquery, soft deletes, a full audit log, and UUID array columns for multi-entity associations.
  The entire stack runs in Docker Compose. Features include paginated/filterable/sortable tables, hardware model associations
  with inline detail overlays, per-record audit history with undo, bulk editing, cross-table full-text search,
  RBAC, Google SSO, and database backup/restore with integrity verification. The frontend communicates exclusively
  through a Next.js BFF proxy that holds the JWT in an httpOnly cookie, keeping the backend URL and credentials off the client
  entirely`,
    href: 'https://github.com/edtbl76/stud.io',
  },
  {
    title: 'Weyland AI/Harness Engineering Lab',
    description: `Weyland AI/Harness Engineering Lab is a self-hosted, multi-node AI platform for engineering and experimentation
    with LLMs, vector databases, graph databases, and data pipelines. The stack spans local LLM inference, embedding generation,
    workflow automation, and Kubernetes (K3s)-managed services.`,
    href: 'https://github.com/edtbl76/weyland-lab',
  },
  {
    title: 'MIDI Real Book',
    description: `MIDI Real Book is a Progressive Web App (PWA) and ensemble reference database cataloging 141+ musical groups
    across jazz, rock, fusion, soul, and classical eras. Each entry covers player profiles, historical timelines, gear, and key
    recordings. Built with Eleventy 3.x and Nunjucks templating, deployed on Firebase Hosting via GitHub Actions CI/CD, with a
    versioned service worker enabling full offline access after first visit. Python handles automated PWA icon generation using
    Pillow and CairoSVG.`,
    href: 'https://github.com/edtbl76/midi_real_book',
    liveSrc: 'https://midi-real-book.web.app/',
  },
  {
    title: 'Algopedia',
    description: `Algopedia is a fun project that I created to help people learn about algorithms and data structures.
    It helps me stay sharp while I revisit old concepts and practice new ones, while also providing context and examples
    for those who are new to the topic. It is 'Code by Ed, Tests by AI', as all tests are initially generated by
    Claude v4. This is one of many ways I practice my craft of prompting and context construction.`,
    href: 'https://github.com/edtbl76/Algopedia',
  },
  {
    title: 'ServiceTransformation',
    description: `This is an example of microservices on k8s. The commit history
    shows the journey through different time periods of service orientation: Netflix
    OSS Stack, Spring, k8s, etc. The goal is to show how the services evolved using
    commit history as a way to understand the evolution of the Service.`,
    href: 'https://github.com/edtbl76/ServiceTransformation',
  },
]

export default projectsData
