interface Project {
  title: string,
  description: string,
  href?: string,
  imgSrc?: string,
}

const projectsData: Project[] = [
  {
    title: 'this site!',
    description: `No fluff, just the good stuff!`,
    imgSrc: '/static/images/emangini-hero.png',
    href: 'https://github.com/edtbl76/emangini-tailwind-nextjs-contentlayer',
  },
  {
    title: 'Algopedia',
    description: `Algopedia is a fun project that I created to help people learn about algorithms and data structures.
    It helps me stay sharp while I revisit old concepts and practice new ones, while also providing context and examples 
    for those who are new to the topic. It is 'Code by Ed, Tests by AI', as all tests are initially generated by 
    Claude v4. This is one of many ways I practice my craft of prompting and context construction.`,
    href: 'https://github.com/edtbl76/Algopedia',
  },
  {
    title: 'Understanding GPT',
    description: `This repository contains a comprehensive guide to understanding GPT (Generative Pre-trained Transformer) models, including detailed explanations, use cases, and implementation examples. Perfect for anyone looking to deepen their knowledge of AI and natural language processing.`,
    imgSrc: '/static/images/gpt.png',
    href: 'https://github.com/edtbl76/UnderstandingGPT',
  },
  {
    title: 'ServiceTransformation',
    description: `This is an example of microservices on k8s. The commit history
    shows the journey through different time periods of service orientation: Netflix
    OSS Stack, Spring, k8s, etc. The goal is to show how the services evolved using
    commit history as a way to understand the evolution of the Service.`,
    href: 'https://github.com/edtbl76/ServiceTransformation',
  },
]

export default projectsData
